on:
   push:
      tags:
         - 'v*'

name: Create Release

jobs:
   autorelease:
      name: Create Release
      runs-on: 'ubuntu-latest'
      steps:
         - name: Checkout code
         uses: actions/checkout@v2
         with:
            fetch-depth: 0
            