on:
   push:
      branches: [master]
   pull-request:
      branches: [master]

name: Tests

defaults:
   run:
      shell: bash

jobs:
   lint:
      name: Lint files
      runs-on: 'ubuntu-latest'
      steps:
         - uses: actions/checkout@v2.3.4
         - uses: actions/setup-go@v2
         with:
            go-version: '1.16'
         - name: golangci-lint
         uses: golangci/golangci-lint-action@2.5.2
         with:
            version: latest

   test:
      name: Run tests
      runs-on: 'ubuntu-latest'
      needs: lint
      steps:
         - uses: actions/checkout@v2.3.4
         - uses: actions/setup-go@v2
         with:
            go-version: '1.16'
         - run: go test -v -cover